[package]
name = "vc-viewer"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1.19"
env_logger = "0.11"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] } 