name: Rust CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/rust.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/rust.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "backend"
      
      - name: Check formatting
        working-directory: ./backend
        run: cargo fmt -- --check
      
      - name: Clippy
        working-directory: ./backend
        run: cargo clippy -- -D warnings
      
      - name: Run tests
        working-directory: ./backend
        run: cargo test --verbose

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "backend"
      
      - name: Build
        working-directory: ./backend
        run: cargo build --verbose
      
      - name: Build release
        working-directory: ./backend
        run: cargo build --release --verbose 